#####################################################################################
version: "3.9"
#####################################################################################
services:
  #####################################################################################
  webservice_api:
    container_name: ${ENV_NAME_WEBSERVICE_API}
    build:
      context: .
      dockerfile: ./webservice_api.Dockerfile
      # target: prod
    labels:
      logging: "promtail" # เพื่อแจ้งให้ promtail ทราบว่าบันทึกของคอนเทนเนอร์ล็อกนี้จะถูกคัดลอก
      logging_jobname: "containerlogs" # กำหนดคอนเทนเนอร์ล็อกให้กับป้ายกำกับงาน
    networks:
      backend:
        ipv4_address: ${ENV_IP_WEBSERVICE_API}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      - ./webservice_api:/app
    restart: always
#####################################################################################
networks:
  backend:
    name: network_service
    external: true # สิ่งนี้จะบอก Docker Compose ให้ถือว่า "เครือข่าย" ที่มีอยู่เป็นเครือข่ายภายนอก

#####################################################################################
