#####################################################################################
version: "3.9"
#####################################################################################
services:
  #####################################################################################
  backup_api:
    container_name: ${ENV_NAME_BACKUP_API}
    build:
      context: .
      dockerfile: ./backup_api.Dockerfile
      target: dev
    networks:
      backend:
        ipv4_address: ${ENV_IP_BACKUP_API}
    volumes:
      - ./backup_api:/app
    restart: always
  #####################################################################################
networks:
  backend:
    name: network_service
    external: true # สิ่งนี้จะบอก Docker Compose ให้ถือว่า "เครือข่าย" ที่มีอยู่เป็นเครือข่ายภายนอก
############################################################

