#####################################################################################
version: "3.9"
#####################################################################################
services:
  #####################################################################################
  portainer:
    container_name: ${ENV_NAME_PORTAINER}
    image: ${ENV_IMAGE_PORTAINER}
    labels:
      logging: "promtail" # เพื่อแจ้งให้ promtail ทราบว่าบันทึกของคอนเทนเนอร์ล็อกนี้จะถูกคัดลอก
      logging_jobname: "containerlogs" # กำหนดคอนเทนเนอร์ล็อกให้กับป้ายกำกับงาน
    networks:
      backend:
        ipv4_address: ${ENV_IP_PORTAINER}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      - /var/run/docker.sock:/var/run/docker.sock
      - /root/secrets/portainer_key:/run/secrets/portainer
      - ./portainer/data:/data
    restart: always
#####################################################################################
networks:
  backend:
    name: network
#####################################################################################
