{
 "title": "Dashboard for Monitor Webservice API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Status Webservice API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Failed step of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 } },
  {
   "title": "Total Status Webservice API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Total Response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Response time for step \"Area : Place_T1_DepartureSecurity\" of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Response time for step \"Area : Place_T2_DepartureSecurity\" of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Total Response HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Response code for step \"Area : Place_T1_DepartureSecurity\" of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Response code for step \"Area : Place_T2_DepartureSecurity\" of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Problem System",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "Response Time ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Area : Place_T1_DepartureSecurity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Response time for step \"Area : Place_T1_DepartureSecurity\" of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Area : Place_T2_DepartureSecurity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BKK : Webservice API" },
     "host": { "filter": "BKK : Webservice API" },
     "item": {
      "filter": "Response time for step \"Area : Place_T2_DepartureSecurity\" of scenario \"RPTS BKK : Web monitoring Webservice API {$WEB.API.URL}\"."
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}